name: CI/CD Pipeline - Wisecow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build and tag Docker image
      - name: Build Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          docker build -t sonukumar2003/wisecow:latest .
          docker tag sonukumar2003/wisecow:latest sonukumar2003/wisecow:$IMAGE_TAG

      # 4. Push Docker image
      - name: Push Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          docker push sonukumar2003/wisecow:latest
          docker push sonukumar2003/wisecow:$IMAGE_TAG

      # 5. Configure kubeconfig
      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > $HOME/.kube/config

      # 6. Smart Kubernetes deployment
      - name: Deploy to Kubernetes
        run: |
          NAMESPACE=wisecow
          DEPLOYMENT=wisecow-deployment
          IMAGE_TAG=${GITHUB_SHA::8}

          # Create namespace if it doesn't exist
          kubectl get namespace $NAMESPACE || kubectl create namespace $NAMESPACE

          # Check if deployment exists
          if kubectl get deployment $DEPLOYMENT -n $NAMESPACE; then
            echo "Updating existing deployment..."
            kubectl set image deployment/$DEPLOYMENT wisecow=sonukumar2003/wisecow:$IMAGE_TAG -n $NAMESPACE
          else
            echo "Creating new deployment..."
            kubectl apply -f k8s-manifests/ -n $NAMESPACE
          fi

          # Wait for rollout and rollback if failed
          if ! kubectl rollout status deployment/$DEPLOYMENT -n $NAMESPACE --timeout=120s; then
            echo "Rollout failed! Rolling back..."
            kubectl rollout undo deployment/$DEPLOYMENT -n $NAMESPACE
            exit 1
          fi
