
name: CI/CD Pipeline - Wisecow

on:
  push:
    branches:
      - main        # Production branch
      - develop     # Staging/CI branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}  # Short SHA
          docker build -t wisecow:$IMAGE_TAG .
          docker tag wisecow:$IMAGE_TAG wisecow:latest

      # 4. Log in to Docker Hub
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Push image to Docker Hub
      - name: Push Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          docker push wisecow:latest
          docker push wisecow:$IMAGE_TAG

      # 6. Deploy to Kubernetes
      - name: Deploy to Kubernetes
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}  # base64 encoded kubeconfig
          IMAGE_TAG: ${{ github.sha }}
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG_DATA" | base64 -d > $HOME/.kube/config

          # Apply manifests
          kubectl apply -f k8s-manifests/

          # Update deployment image with rollback if failed
          if ! kubectl set image deployment/wisecow-deployment wisecow=wisecow:$IMAGE_TAG --record || ! kubectl rollout status deployment/wisecow-deployment; then
            echo "Deployment failed! Rolling back..."
            kubectl rollout undo deployment/wisecow-deployment
            exit 1
          fi
