name: CI/CD Pipeline - Wisecow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & tag Docker image
      - name: Build Docker image
        run: |
          docker build -t sonukumar2003/wisecow:latest .
          docker tag sonukumar2003/wisecow:latest sonukumar2003/wisecow:${{ github.sha }}

      # Push Docker image
      - name: Push Docker image
        run: |
          docker push sonukumar2003/wisecow:latest
          docker push sonukumar2003/wisecow:${{ github.sha }}

      # Setup kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Configure kubeconfig from secret
      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > $HOME/.kube/config

      # Deploy to Kubernetes
      - name: Deploy Wisecow to Kubernetes
        run: |
          kubectl set image deployment/wisecow-deployment wisecow=sonukumar2003/wisecow:${{ github.sha }} --record || kubectl apply -f k8s-manifests/
          kubectl rollout status deployment/wisecow-deployment
